core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categorias/', include('category.urls')),
    path('produtos/', include('products.urls')),
    path('resultado/', include('filter.urls')),
    path('search/', include('search.urls')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/search/urls.py
from django.urls import path
from .views import SearchProductView

app_name = 'search'

urlpatterns = [
    path('', SearchProductView.as_view(), name='query')
]

core/search/models.py
from django.db import models

# Create your models here.

core/search/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from products.models import Product
from django.db.models import Q
from products.utils import FilterPrice


class SearchProductView(ListView):
    template_name = 'search/search.html'
    paginate_by = 20


    def get_queryset(self, *args, **kwargs):
        global price

        query = self.request.GET.get('q', None)
        queryset = Product.search.q(query)

        price = FilterPrice(queryset)

        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        context['price'] = price
        return context

core/templates/search/form.html
<form method="get" action={% url 'search:query' %} class="inline form col-lg-8"> 
	<input class="entrar" type="search" placeholder="pesquisar" maxlength="100" name="q" value="{{ request.GET.q }}">
		<button class="tamanho">
			<i class="fa fa-search" aria-hidden="true"></i>
		</button>
</form>

core/templates/search/search.html
{% extends 'base.html' %}
{% load static %}
{% block title_ %}buscar produto{% endblock %}

{%block base_head %}
<link rel="stylesheet" type="text/css" href="{% static 'products/css/card.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'products/css/product_card.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'products/css/filter.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'products/css/modal.css' %}">
{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		{% if  object_list.exists %}
		<div class="col-lg-3">
		{% if view.request.user_agent.is_mobile or view.request.user_agent.is_tablet %}
			<div class="btn-modal">
				<div class="justify-content-center border-bottom line">
					 <a href="#" class="no-decoration" id="myBtn">&#8644;Filtrar</a>
				</div>
			</div>
		{% endif %}

		{% if view.request.user_agent.is_mobile or view.request.user_agent.is_tablet %}
			{% include 'search/includes/modal_filter.html'%}
		{% endif %}

			<h2>{{ query|title }}</h2>
			<p class="result"> {{ price.result_count }} resultado</p>

		{% if view.request.user_agent.is_pc %}
			{% include 'search/includes/filter.html' %}
		{% endif %}

		</div>
		<div class="col-lg-9">
			{% include 'products/includes/card.html' %}
		</div>
		{% else %}
		<p>Nenhum Para <del>{{ query }}</del> </p>
		{% endif %}
	</div>
</div>
{% if object_list.exists %}
{% include 'products/includes/pagination.html' %}
{% endif %}
{% endblock %}
{% block scripts %}
	<script type="text/javascript" src="{% static 'products/js/modal.js' %}"></script>
	<script type="text/javascript" src="{% static 'products/js/dropdown.js' %}"></script>
{% endblock %}