core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categorias/', include('category.urls')),
    path('produtos/', include('products.urls')),
    path('resultado/', include('filter.urls')),
    path('search/', include('search.urls')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/filter/urls.py
from django.urls import path
from .views import FilterProductView, FilterSearchView

app_name = "filter"

urlpatterns = [
    path(
        "<slug:slug>_mais<int:price_gt>_menos<int:price_lt>/",
        FilterProductView.as_view(),
        name="result",
    ),
    path(
        "ss/<query>_mp<int:price_gt>_ml<int:price_lt>/",
        FilterSearchView.as_view(),
        name="search",
    ),
]

core/products/urls.py
from django.urls import path
from .views import (
    ProductFormView,
    ListProductView,
    ProductDetailView,
    edit_product,
    ProductDeleteView,
)
from rolepermissions.decorators import has_permission_decorator


app_name = "products"

urlpatterns = [
    path(
        "add-produto",
        has_permission_decorator("add_product")(ProductFormView.as_view()),
        name="add_product",
    ),
    path("todos/", ListProductView.as_view(), name="list_product"),
    path("see/<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path(
        "edit/<pk>/",
        has_permission_decorator("edit_product")(edit_product),
        name="edit",
    ),
    path(
        "apagar/<int:pk>/",
        has_permission_decorator("delete_product")(ProductDeleteView.as_view()),
        name="delete",
    ),
]

core/products/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from django.urls import reverse
from model_utils.models import TimeStampedModel
from django.db.models.signals import pre_save
from auditlog.registry import auditlog
from auditlog.models import AuditlogHistoryField
from decimal import Decimal
from datetime import date
from django.db.models import Q


# filtrar todos os produtos que estam disponíveis
class AvailableManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_available=True)


# search products by name and description
class SearchManager(models.Manager):
    def q(self, query):
        lookups = (
            Q(name__icontains=query)|
            Q(description__icontains=query)
        )

        return super().get_queryset().filter(lookups, is_available=True)


class Category(TimeStampedModel):
    name = models.CharField(max_length=255, unique=True)
    slug = AutoSlugField(unique=True, populate_from="name")
    image = models.ImageField("category/img", blank=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:list_by_category", kwargs={"slug": self.slug})


class Product(TimeStampedModel):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=800)
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    slug = AutoSlugField(populate_from="name", unique=False)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    is_available = models.BooleanField(default=True)
    image = models.ImageField(upload_to="products/img/", blank=True)
    objects = models.Manager()
    available = AvailableManager()
    offer_available = models.BooleanField(default=False)
    offer_price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    rebate = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    offer_time = models.DateField(auto_now=True)
    history = AuditlogHistoryField()
    search = SearchManager()

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"slug": self.slug})


class ImageProduct(models.Model):
    product = models.ForeignKey(Product, related_name="images", on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='products/photo/', blank=True)

    def __str__(self):
        return self.product.name


def pre_save_offer_price(sender, instance, **kwargs):
    if instance.rebate > 0:
        instance.offer_price = Decimal(instance.price) - Decimal(instance.rebate)


pre_save.connect(pre_save_offer_price, sender = Product)

auditlog.register(Product, include_fields=['price', 'offer_price', 'rebate',])

core/products/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Product, Category, ImageProduct

class ProductForm(forms.ModelForm):
    image = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={"multiple": True, "class": "d-none", "onchange": "image_select();"}
        )
    )
    name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}),
        max_length=100,
        required=True,
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control"}),
        max_length=500,
        required=True,
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={"class": "form-select"}),
    )

    class Meta:
        model = Product
        fields = ("name", "description", "category", "price", "is_available", "image")


# custom widget
class CustomClearableFileInput(forms.ClearableFileInput):
    template_name = 'widgets/customclearablefileinput.html'


class ImageForm(forms.ModelForm):
    photo = forms.ImageField(
        widget=CustomClearableFileInput(attrs={"class":"d-none"})
    )
    class Meta:
        model = ImageProduct
        fields = ('photo',)


# formset to update imageprodut
ImageProductFormset = inlineformset_factory(
    Product,
    ImageProduct,
    form=ImageForm,
    extra=0,
    can_delete=False,
    min_num=0,
    validate_min=True,
    fields=('photo',)
)

core/filter/views.py
from django.views.generic.list import ListView
from products.models import Product, Category
from django.shortcuts import get_object_or_404
from products.utils import FilterPrice
from django.db.models import Max


class FilterProductView(ListView):
    template_name = "products/products_list.html"
    paginate_by = 20

    def get_queryset(self):
        # var global get_context_data
        global price

        queryset = Product.available.all()
        category_slug = self.kwargs.get("slug")

        # pegando os valores do form
        gt = self.kwargs.get("price_gt")  # great than
        lt = self.kwargs.get("price_lt")  # less than

        if not gt:
            gt = 0
        # gt can't lt
        if not lt or int(gt) > int(lt):
            lt = 1000000

        if category_slug:
            self.category = get_object_or_404(Category, slug=category_slug)
            queryset = queryset.filter(
                category=self.category, price__gt=gt, price__lte=lt
            )
        # get filter price
        if queryset.exists():
            price = FilterPrice(queryset)
        else:
            price = 0

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["slug"] = self.kwargs.get("slug")
        context["price"] = price
        return context


class FilterSearchView(ListView):
    template_name = "search/search.html"
    paginate_by = 20

    def get_queryset(self):
        # var global get_context_data
        global price

        query = self.kwargs.get("query")

        # pegando os valores do form
        gt = self.kwargs.get("price_gt")  # great than
        lt = self.kwargs.get("price_lt")  # less than

        if not gt:
            gt = 0
        # gt can't lt
        if not lt or int(gt) > int(lt):
            lt = 1000000

        queryset = Product.search.q(query)
        queryset = queryset.filter(
            price__gt=gt, price__lte=lt
        )

        # get filter price
        if queryset.exists():
            price = FilterPrice(queryset)
        else:
            price = 0

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.kwargs.get("query")
        context["price"] = price
        return context

core/products/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.views.generic.edit import FormView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import Category, Product, ImageProduct
from .forms import ProductForm, ImageForm, ImageProductFormset
from django.urls import reverse_lazy
from django.db.models import Max


class ProductFormView(FormView):
    template_name = 'products/product_form.html'
    form_class = ProductForm
    success_url = reverse_lazy('category:categories')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('image') # get images

        if form.is_valid():
            # get product
            product = form.save()
            # for list of images
            for f in files:
                # create images relationships product
                ImageProduct.objects.create(product=product, photo=f)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class ListProductView(ListView):
    template_name = 'products/products_list.html'
    paginate_by = 20

    def get_queryset(self):
        queryset = Product.available.all()

        return queryset


class ProductDetailView(DetailView):
    model = Product


def edit_product(request, pk):
    product = Product.objects.get(pk=pk)

    if request.method == 'POST':
        form = ProductForm(request.POST or None, request.FILES or None, instance=product)
        formset = ImageProductFormset(request.POST or None, request.FILES or None, instance=product)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect('products:detail', slug=product.slug)
    else:
        form = ProductForm(instance=product)
        formset = ImageProductFormset(instance=product)

    context = {
        'form': form,
        'product': product,
        'formset': formset
    }

    return render(request, 'products/edit_product.html', context)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('category:categories')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

core/templates/products/includes/card.html
{% for product in object_list %}
	<div class="col mobile">
		<div class="card card-line">
            <a class="center-img" href="{{ product.get_absolute_url }}">
				<img src="{{ product.images.first.photo.url }}" class="ajuste-img" alt="Sua internet é uma bosta!">
			</a>
			<div class="card-body" style="width:50%">
				<a class='cor' href="{{ product.get_absolute_url }}">
				<p class="card-title name-font truncate mobile-font">{{ product.name|title }}</p>
				<p class="card-text price-font">
					<span>R$</span> {{ product.price }}
				</p>
				</a>
			</div>
		</div>
	</div>
{% endfor %}

core/templates/products/includes/delete.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
 Deletar 
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Deletar produto</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
         <form method="POST" action="{% url "products:delete" pk=pk %}">
            {% csrf_token %}
            <p>Deletar produto: {{ object.name }}</p>
            <input type="submit" class="btn btn-danger" value="DELETAR">
         </form>
      </div>
    </div>
  </div>
</div>

core/templates/products/includes/filter.html
  <div class="desktop">
    <div>
      Preço 
    </div>
    
    <ul class="list-group list-group-flush">  
      <li class="non-st"><a class="cor" href="{% url 'filter:result' slug=slug price_gt=1 price_lt=price.price1 %}">até R${{ price.price1 }}</a></li>
      {% if price.bitween_price %}
      <li class="non-st"><a class="cor" href="{% url 'filter:result' slug=slug price_gt=price.price1 price_lt=price.price2 %}">R${{ price.price1 }} a R${{ price.price2 }}</a></li>
      {% endif %}
      {% if object_list.count > 1 and price.price2 != price.max_price  %}
      <li class="non-st"><a class="cor" href="{% url 'filter:result' slug=slug price_gt=price.price2 price_lt=price.max_price %}">Mais de R${{ price.price2 }}</a></li>
      {% endif %}
    </ul>
  </div>

core/templates/products/includes/img_detail.html
<div class="row col-8">
<div class="col-1 justify-content-center align-top" >
	{% for img in object.images.all %}
		<div class=" gallery" >
			<img class="tab" src="{{ img.photo.url }}" alt="not back" onclick="myFunction(this);">
		</div>
	{% endfor %}
</div>
<div class="col-11">
	<div class="photo-center">
		<img class="photo-ajust" src="{{ object.images.first.photo.url }}" id="expandedImg" alt="not back">
	</div>
</div>
</div>

core/templates/products/includes/mobile_img_detail.html
<!-- Full-width images with number text -->
{% for img in object.images.all %}
  <div class="mySlides photo-center-mobile">
    <div class="numbertext">{{ forloop.counter }} / {{ object.images.count }}</div>
    <img class="photo-ajust" src="{{ img.photo.url }}">
  </div>
{% endfor %}


  <!-- Next and previous buttons -->
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>

core/templates/products/includes/modal_filter.html
<!-- The Modal -->
<div id="myModal" class="modal-own">

  <!-- Modal content -->
  <div class="modal-content-own">
    <div class="modal-header">
      <span class="close-own">&times;</span>
      <h1>Filtrar</h1>
    </div>
    <div class="modal-body">
      <div>
        <div class="border-bottom" style="height: 30px;">
          <p id="open">Preço <i class="fa fa-chevron-down arrow-right"></i></p>
        </div>
        
        <ul class="list-group list-group-flush border-bottom" id="dropdown">  
          <li class="non-st">
            <a class="no-decoration" href="{% url 'filter:result' slug=slug price_gt=1 price_lt=price.price1 %}">até R${{ price.price1 }}</a>
          </li>
          {% if price.bitween_price %}
          <li class="non-st">
            <a class="no-decoration" href="{% url 'filter:result' slug=slug price_gt=price.price1 price_lt=price.price2 %}">R${{ price.price1 }} a R${{ price.price2 }}</a>
          </li>
          {% endif %}
          {% if object_list.count > 1 and price.price2 != price.max_price  %}
          <li class="non-st">
            <a class="no-decoration" href="{% url 'filter:result' slug=slug price_gt=price.price2 price_lt=price.max_price %}">Mais de R${{ price.price2 }}</a>
          </li>
          {% endif %}
        </ul>
      </div> 
    </div>
  </div>

</div>

core/templates/products/includes/pagination.html
<div class="container" style="margin-top: 30px;">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center align-items-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&#10094; Anterior</a>
                </li>
            {% endif %}

            <li class="page-item" style="padding: 0px 20px 0px 20px">
                <strong style="padding-right: 15px;">{{ page_obj.number }}</strong> de {{ page_obj.paginator.num_pages }}
            </li>

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Seguinte &#10095;</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>