core/category/urls.py
from django.urls import path
from .views import CategoryView, CategoryProductView, CategoryFormView
from rolepermissions.decorators import has_permission_decorator
from django.views.decorators.cache import cache_page

app_name = "category"

urlpatterns = [
    path("", cache_page(60*15)(CategoryView.as_view()), name="categories"),
    path('list/<slug:slug>/', CategoryProductView.as_view(), name='category_list'),
    path(
        'criar/',
        has_permission_decorator('add_category')(CategoryFormView.as_view()),
        name='add_category'
    ),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categorias/', include('category.urls')),
    path('produtos/', include('products.urls')),
    path('resultado/', include('filter.urls')),
    path('search/', include('search.urls')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/products/urls.py
from django.urls import path
from .views import (
    ProductFormView,
    ListProductView,
    ProductDetailView,
    edit_product,
    ProductDeleteView,
)
from rolepermissions.decorators import has_permission_decorator


app_name = "products"

urlpatterns = [
    path(
        "add-produto",
        has_permission_decorator("add_product")(ProductFormView.as_view()),
        name="add_product",
    ),
    path("todos/", ListProductView.as_view(), name="list_product"),
    path("see/<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path(
        "edit/<pk>/",
        has_permission_decorator("edit_product")(edit_product),
        name="edit",
    ),
    path(
        "apagar/<int:pk>/",
        has_permission_decorator("delete_product")(ProductDeleteView.as_view()),
        name="delete",
    ),
]

core/templates/components/baseboard.html
<div class="mt-5">
	<footer class="justify-content-center base">
		<ul>
			<li class="cor-w">
				<a href="https://instagram.com/the_vinicius_3d/" target="_blank"><span><i class="fa fa-instagram" aria-hidden="true"></i></span></a> Vinicius-3D
			</li>
			<li class="cor-w">
				<a href="https://instagram.com/d_acessorios_multimarcas/" target="_blank"><span><i class="fa fa-instagram" aria-hidden="true"></i></span></a> D&E
			</li>
		</ul>
		<div class="justify-content-center d-flex">
			<a href="{% url 'home' %}">Home</a>
		</div>
		<p class="copy">
			Copyright &#169; Vinicius-3D
		</p>

	</footer>
</div>

core/templates/components/display.html
{% load static %}
<div style="height: 400px;">
	<div class="mySlides photo-center h-100">
		<img class="photo-ajust m-h-400" src="{% static 'home/roupas'%}" alt="loira">
	</div>
	<div class="mySlides photo-center show-image h-100">
		<img class="photo-ajust m-h-400" src="{% static 'home/celular.png'%}" alt="acessorios">
	</div>
	<div class="mySlides photo-center show-image h-100">
		<img class="photo-ajust m-h-400" src="{% static 'home/capinha.jpg'%}" alt="capinha">
	</div>
</div>

core/templates/components/navbar.html
{% load permission_tags %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">D&E</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    	<ul class="navbar-nav me-auto mb-2 mb-lg-0">
    		<li class="nav-item">
    			<a class="nav-link" href="{% url 'category:categories' %}">Categorias</a>
    		</li>
            {% if user|has_role:'gerente' %}
    		<li class="nav-item">
                <a class="nav-link" href="{% url 'products:add_product' %}">Adicionar produtos</a>
    		</li>
    		<li class="nav-item">
    			<a class="nav-link" href="{% url 'category:add_category' %}">Criar categoria</a>
    		</li>
            {% endif %}
            {% if  request.user.is_superuser %}
			<li class="nav-item">
    			<a class="nav-link" href="/admin/">Admin</a>
    		</li>
            {% endif %}
    	</ul>
        {% include 'search/form.html' %}
    </div>
  </div>
</nav>