core/category/urls.py
from django.urls import path
from .views import CategoryView, CategoryProductView, CategoryFormView
from rolepermissions.decorators import has_permission_decorator
from django.views.decorators.cache import cache_page

app_name = "category"

urlpatterns = [
    path("", cache_page(60*15)(CategoryView.as_view()), name="categories"),
    path('list/<slug:slug>/', CategoryProductView.as_view(), name='category_list'),
    path(
        'criar/',
        has_permission_decorator('add_category')(CategoryFormView.as_view()),
        name='add_category'
    ),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categorias/', include('category.urls')),
    path('produtos/', include('products.urls')),
    path('resultado/', include('filter.urls')),
    path('search/', include('search.urls')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/category/forms.py
from django import forms
from products.models import Category

class CategoryForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}),
        max_length=100,
        required=True,
    )
    image = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={"class": "d-none", "onchange": "image_select();"}
        )
    )

    class Meta:
        model = Category
        fields = ('name', 'image')

core/category/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from products.models import Category, Product
from products.utils import FilterPrice
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from .forms import CategoryForm


class CategoryView(ListView):
    queryset = Category.objects.all()
    paginate_by = 12
    template_name = 'category/category_list.html'


class CategoryProductView(ListView):
    template_name = 'products/products_list.html'
    paginate_by = 20

    def get_queryset(self):
        # var global get_context_data
        global price

        queryset = Product.available.all()
        category_slug = self.kwargs.get('slug')

        if category_slug:
            self.category = get_object_or_404(Category, slug=category_slug)
            queryset = queryset.filter(category=self.category)

        # get filter price
        price = FilterPrice(queryset)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['price'] = price
        context['slug'] = self.kwargs.get('slug')
        return context


class CategoryFormView(FormView):
    template_name = 'category/category_form.html'
    form_class = CategoryForm
    success_url = reverse_lazy('category:categories')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

core/templates/category/category_form.html
{% extends 'base.html' %}
{% load static %}
{% block title_ %}criar categoria{% endblock %}

{% block base_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'products/css/add_product.css' %}">
{% endblock %}

{% block content %}
<div class="container justify-content-center d-flex">
	<form method="post" enctype="multipart/form-data" id="form">{% csrf_token %}
		<p class="display-6">Criar uma Categoria:</p>
		<div class="w-max">
			{{ form.name.errors }}
			<label for="{{ form.name.id_for_label }}">Nome:</label>
			{{ form.name }}
		</div>
		<div class="card shadow-sm w-max">
	        <div class="card-header d-flex justify-content-between">
	            <h4>Imagem</h4>
	                {{ form.image }}
	                <button class="btn btn-sm btn-primary" onclick="document.getElementById('id_image').click()" type="button">Escolhe imagem</button>
	        </div>
	        <div class="card-body d-flex flex-wrap justify-content-center" id="container">
	        </div>
	    </div>
	    <input class="btn btn-lg btn-success" type="submit" value="Salvar">
	</form>
</div>
{% endblock %}
{% block scripts %}
	<script type="text/javascript" src="{% static 'products/js/add_product.js' %}"></script>
{% endblock %}

core/templates/category/category_list.html
{% extends 'base.html' %}
{% load static %}
{% load permission_tags %}
{% block title_ %}categorias{% endblock %}

{%block base_head %}
<link rel="stylesheet" type="text/css" href="{% static 'products/css/card.css' %}">
{% endblock %}
{% block content %}
{% if object_list.exists %}
<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-xl-9">
			<p class="fs">Produtos separados por categorias:</p>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-xl-9">
			<div class="row-cols-xl-3 row-cols-lg-3 row-cols-md-2 row-cols-sm-2 row-cols-1 row">
					{% for category in object_list %}
					<div class="col" style="margin-top: 10px;">
						<div class="category">
							<div class="card card-size">
		                        <a class="cor" href="{% url 'category:category_list' slug=category.slug %}">
									<div>
										<img class="img-center" src="{{ category.image.url }}" class="card-img-bottom" alt="...">
									</div>
								</a>
							</div>
							<a class="cor" href="{% url 'category:category_list' slug=category.slug %}">
							<div class="card-footer border border-1">
								<h5 class="text-center">{{ category.name|title }}</h5>
							</div>
							</a>
						</div>

					</div>
					{% endfor %}
			</div>
		</div>
	</div>
	<br>
    {% include 'products/includes/pagination.html' %} 
</div> 
{% else %}
	{% if user|has_role:'gerente' %}
		<div class="container d-flex justify-content-center">
			<a class="btn btn-primary" href="{% url 'category:add_category' %}"> criar uma categoria</a>
		</div>
	{% else %}
		<div class="container">
			<p>Nenhuma categoria foi criada</p>
		</div>
	{% endif %}
{% endif %}
{% endblock %}